'use strict';
const fs = require('fs');
const path = require('path');
const os = require('os');

// ═══════════════════════════════════════════════════════════════
//  CODE REWRITER — Builds Custom Model & Rewrites Core Code 🧬💻
// ═══════════════════════════════════════════════════════════════

class CodeRewriter {
  constructor(config, provider, memory) {
    this.config = config;
    this.provider = provider;
    this.memory = memory;
    this.srcDir = path.join(__dirname, '..');
    this.rewriteLog = [];
    this.customModelDir = path.join(os.homedir(), '.opendesktop', 'custom-model');
    this.knowledgeBase = path.join(os.homedir(), '.opendesktop', 'knowledge-base');
    [this.customModelDir, this.knowledgeBase].forEach(d => { if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true }); });
  }

  // ─── ANALYZE & REWRITE ───
  async analyzeAndRewrite(targetFile, goal) {
    if (!fs.existsSync(targetFile)) return { error: `File ${targetFile} not found` };

    const original = fs.readFileSync(targetFile, 'utf8');
    const analysis = await this.provider.chat(
      `Analyze this code and suggest improvements for: ${goal}\n\nCode:\n\`\`\`javascript\n${original}\n\`\`\`\n\nProvide:\n1. Issues found\n2. Performance improvements\n3. Feature additions\n4. Code structure improvements\n5. The COMPLETE improved code\n\nReturn the improved code in a code block.`,
      { maxTokens: 8000 }
    );

    const codeMatch = analysis.match(/```(?:javascript)?\n([\s\S]*?)```/);
    const improvedCode = codeMatch ? codeMatch[1].trim() : null;

    return { file: targetFile, goal, analysis, improvedCode, timestamp: new Date().toISOString() };
  }

  // ─── SAFE REWRITE WITH BACKUP ───
  async safeRewrite(targetFile, goal) {
    const backupDir = path.join(os.homedir(), '.opendesktop', 'backups', `rewrite_${Date.now()}`);
    if (!fs.existsSync(backupDir)) fs.mkdirSync(backupDir, { recursive: true });

    const original = fs.readFileSync(targetFile, 'utf8');

    const result = await this.analyzeAndRewrite(targetFile, goal);
    if (!result.improvedCode) return { error: 'Could not generate improved code', analysis: result.analysis };

    // Backup original
    const backupPath = path.join(backupDir, path.basename(targetFile));
    fs.writeFileSync(backupPath, original);

    // Write improved code
    fs.writeFileSync(targetFile, result.improvedCode);

    this.rewriteLog.push({ file: targetFile, goal, backup: backupPath, timestamp: new Date().toISOString() });
    this.memory.addEvent({ type: 'code-rewrite', file: targetFile, goal });

    return { success: true, file: targetFile, backup: backupPath, linesChanged: Math.abs(original.split('\n').length - result.improvedCode.split('\n').length) };
  }

  // ─── BUILD CUSTOM KNOWLEDGE BASE ───
  async buildKnowledgeBase(topic, sources) {
    const knowledge = await this.provider.chat(
      `Build a comprehensive knowledge base about: ${topic}\n${sources ? 'Sources: ' + sources.join(', ') : ''}\n\nStructure as:\n1. Core concepts\n2. Key facts\n3. Best practices\n4. Common patterns\n5. Pitfalls to avoid\n6. Resources\n7. Quick reference\n\nBe thorough and factual.`,
      { maxTokens: 8000 }
    );

    const kbFile = path.join(this.knowledgeBase, `${topic.replace(/\s+/g, '-').toLowerCase()}.md`);
    fs.writeFileSync(kbFile, `# Knowledge Base: ${topic}\n\n${knowledge}\n\n---\n*Generated by OpenDesktop on ${new Date().toISOString()}*`);

    return { topic, file: kbFile, timestamp: new Date().toISOString() };
  }

  // ─── CUSTOM MODEL TRAINING DATA ───
  async generateTrainingData(task, examples) {
    const trainingData = await this.provider.chat(
      `Generate training data for: ${task}\n${examples ? 'Example format: ' + JSON.stringify(examples[0]) : ''}\n\nGenerate 50 high-quality training examples as JSON array: [{"input": "...", "output": "..."}]\nMake them diverse, accurate, and cover edge cases.`,
      { maxTokens: 8000 }
    );

    try {
      const data = JSON.parse(trainingData.match(/\[[\s\S]*\]/)?.[0] || '[]');
      const dataFile = path.join(this.customModelDir, `${task.replace(/\s+/g, '-').toLowerCase()}_training.json`);
      fs.writeFileSync(dataFile, JSON.stringify(data, null, 2));
      return { task, examples: data.length, file: dataFile };
    } catch {
      return { task, raw: trainingData, note: 'Could not parse as JSON, saved raw response' };
    }
  }

  // ─── SELF-MODIFICATION ───
  async selfModify(moduleName, instruction) {
    const modulePath = path.join(this.srcDir, moduleName, 'index.js');
    if (!fs.existsSync(modulePath)) return { error: `Module ${moduleName} not found` };

    const currentCode = fs.readFileSync(modulePath, 'utf8');
    const result = await this.provider.chat(
      `You are modifying your own code. Module: ${moduleName}\nCurrent code:\n\`\`\`javascript\n${currentCode}\n\`\`\`\n\nInstruction: ${instruction}\n\nIMPORTANT: Return the COMPLETE modified code. Keep all exports. Make it better. Don't break existing functionality.`,
      { maxTokens: 8000 }
    );

    const codeMatch = result.match(/```(?:javascript)?\n([\s\S]*?)```/);
    if (!codeMatch) return { error: 'Could not extract code from response' };

    const newCode = codeMatch[1].trim();
    if (newCode.length < 100) return { error: 'Generated code too short' };

    // Backup
    const backup = path.join(os.homedir(), '.opendesktop', 'backups', `self-mod_${moduleName}_${Date.now()}.js`);
    const backupDir = path.dirname(backup);
    if (!fs.existsSync(backupDir)) fs.mkdirSync(backupDir, { recursive: true });
    fs.copyFileSync(modulePath, backup);

    // Apply modification
    fs.writeFileSync(modulePath, newCode);

    this.rewriteLog.push({ module: moduleName, instruction, backup, timestamp: new Date().toISOString() });
    this.memory.addEvent({ type: 'self-modification', module: moduleName, instruction });

    return { success: true, module: moduleName, backup, timestamp: new Date().toISOString() };
  }

  // ─── FEATURE ADDITION ───
  async addFeature(moduleName, featureDescription) {
    const modulePath = path.join(this.srcDir, moduleName, 'index.js');
    if (!fs.existsSync(modulePath)) return { error: `Module ${moduleName} not found` };

    const currentCode = fs.readFileSync(modulePath, 'utf8');
    const result = await this.provider.chat(
      `Add this feature to the module:\nFeature: ${featureDescription}\n\nCurrent code:\n\`\`\`javascript\n${currentCode}\n\`\`\`\n\nAdd the feature while keeping all existing functionality. Return the COMPLETE updated code.`,
      { maxTokens: 8000 }
    );

    const codeMatch = result.match(/```(?:javascript)?\n([\s\S]*?)```/);
    if (!codeMatch) return { error: 'Could not extract code' };

    const newCode = codeMatch[1].trim();
    const backup = path.join(os.homedir(), '.opendesktop', 'backups', `feature-add_${moduleName}_${Date.now()}.js`);
    fs.copyFileSync(modulePath, backup);
    fs.writeFileSync(modulePath, newCode);

    return { success: true, module: moduleName, feature: featureDescription, backup };
  }

  // ─── UNIVERSAL CONNECTIVITY ───
  async connectTo(service, credentials) {
    const connectionScript = await this.provider.chat(
      `Write a Node.js module to connect to ${service}.\n${credentials ? 'Credentials available: ' + Object.keys(credentials).join(', ') : 'Use environment variables for auth.'}\n\nInclude:\n1. Connection setup\n2. Common operations\n3. Error handling\n4. Auto-reconnect\n\nReturn as a complete module with module.exports.`,
      { maxTokens: 4096 }
    );

    const codeMatch = connectionScript.match(/```(?:javascript)?\n([\s\S]*?)```/) || [null, connectionScript];
    const connectorFile = path.join(this.customModelDir, `connector-${service.toLowerCase().replace(/\s+/g, '-')}.js`);
    fs.writeFileSync(connectorFile, codeMatch[1].trim());

    return { service, connector: connectorFile, timestamp: new Date().toISOString() };
  }

  getRewriteLog() { return this.rewriteLog; }
  getKnowledgeBase() { return fs.readdirSync(this.knowledgeBase).filter(f => f.endsWith('.md')); }
}

module.exports = CodeRewriter;
